### ISSUE TITLE
Incorrect launchOptions type for Swift 3

### ISSUE THREAD

**Issue by AnthonyOliveri** [ibm-bluemix-mobile-services/bms-clientsdk-swift-security-facebookauthentication#10]
In the `onFinishLaunching` method, the `launchOptions` parameter should have the type `[UIApplicationLaunchOptionsKey: Any]?`, not `[NSObject: AnyObject]?`.

**Comment by vitalymibm** [comment]
@AnthonyOliveri 
Fixed and published release v2.0.2
