### ISSUE TITLE
Sample app does not work in Xcode 8

### ISSUE THREAD

**Issue by AnthonyOliveri** [ibm-bluemix-mobile-services/bms-clientsdk-swift-security-facebookauthentication#11]
When opening the sample FacebookMCA app in Xcode 8, the "Convert to Current Swift Syntax?" prompt appears, and the project fails to build.

**Comment by vitalymibm** [comment]
Fixed compilation issues and set Swift 3 language as default in the project file. Note that you need to run pod install and copy FacebookAuthenticationManager.swift from Pods to the project.
