### ISSUE TITLE
Fails to build in Xcode 7.3 projects with FBSDKCoreKit 4.18.0

### ISSUE THREAD

**Issue by AnthonyOliveri** [ibm-bluemix-mobile-services/bms-clientsdk-swift-security-facebookauthentication#21]
This looks like an issue with the Facebook SDK rather than BMSFacebookAuthentication. I would open an issue there, but the developers do not have an Issue tab and [do not seem to care about supporting anything but the latest Xcode version](https://github.com/facebook/facebook-ios-sdk/pull/846). So I am putting the issue here to bring it to your attention. Perhaps the `.podspec` can be modified to require FBSDKCoreKit and FBSDKLoginKit 4.9.0 --> 4.17.0, since 4.18.0 is broken for Xcode 7.3.

**Comment by odedBetzalel** [comment]
Changed the podspec file to take version 4.17 up to and not including 4.18 for both FBSDKCoreKit and FBSDKLoginKit
